clear

export EDITOR="code --wait"
export DOTFILES=${HOME}/Documents/dotfiles

autoload -U colors && colors

# enable tab-completion in cd path
autoload -U compinit && compinit

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

function reload() {
  . ~/.zshrc
}

# update ssh key used for github, e.g. for switching between personal and work accounts
# usage: github-key [path-to-key]
# if no path is provided, defaults to ~/.ssh/id_ed25519
function github-key() {
  ssh-add -D

  if [ ! -f ~/.ssh/config ]; then
    touch ~/.ssh/config
  fi

  local new_key_path=${1:-${HOME}/.ssh/id_ed25519}

  if grep -q "Host github.com" ~/.ssh/config; then
    awk -v new_key_path="$new_key_path" '
      $1 == "Host" && $2 == "github.com" { in_github_host=1 }
      in_github_host && $1 == "IdentityFile" { $2 = new_key_path; in_github_host=0 }
      { print }
    ' ~/.ssh/config > ~/.ssh/config.tmp && mv ~/.ssh/config.tmp ~/.ssh/config
  else
    echo "\nHost github.com\n  IdentityFile $new_key_path" >> ~/.ssh/config
  fi

  ssh-add ${new_key_path}
  ssh -T git@github.com
}

# Load secrets not tracked in git for security, etc.
for secret_config in ${DOTFILES}/etc/secret/*.zsh; do
  source $secret_config
done

# Load all config files
for config_file in ${DOTFILES}/etc/*.zsh; do
  source $config_file
done

eval "$(rbenv init -)"
eval "$(nodenv init -)"
eval "$(pyenv init --path)"

export HISTSIZE=10000
export SAVEHIST=10000

# prevent vscode vim bindings from mucking with ctr-a etc
# https://code.visualstudio.com/docs/editor/integrated-terminal#_ctrla-ctrlr-output-a-r-on-zsh
bindkey -e

# case-insensitive tab autocomplete
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

setopt prompt_subst
PROMPT='%1d %{$fg[cyan]%}⤏ %{$reset_color%} '

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
